# PostgreSQL Connection

# Docker compose
# spring.datasource.url=jdbc:postgresql://postgres:5432/blogdb

#local
spring.datasource.url=jdbc:postgresql://localhost:5432/blogdb


spring.datasource.username=user
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# flyway
spring.flyway.enabled=true
# spring.flyway.clean-disabled=false # mvn flyway:clean

# logging.level.org.springframework.security=DEBUG

api.security.token.secret=${JWT_SECRET:minha-chave-secreta-2026}